# Generated by Django 5.2.2 on 2025-07-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('management', 'Management'), ('ai', 'AI')], default='coding', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('retracted', 'Retracted'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='positions.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_pct', models.PositiveIntegerField(default=50, help_text='Required proficiency % (0–100)')),
                ('importance', models.PositiveSmallIntegerField(default=1, help_text='Relative importance (1–5)')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='positions.position')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='positions.skill')),
            ],
            options={
                'unique_together': {('position', 'skill')},
            },
        ),
    ]
